import { Footer } from '@/components/footer';
import { Navbar } from '@/components/navbar';
import { cn } from '@/lib/utils';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('relative', inter.className)}>
        {/* Background Grid */}
        <div className="container absolute left-1/2 top-0 z-0 h-full -translate-x-1/2 ">
          <div className="absolute left-0 top-0 z-0 grid h-full w-full grid-cols-2 px-8 md:grid-cols-4 lg:grid-cols-6">
            <div className="h-full w-full border-l border-dashed border-zinc-200" />
            <div className="hidden h-full w-full border-l border-dashed border-zinc-200 lg:block" />
            <div className="hidden h-full w-full border-l border-dashed border-zinc-200 lg:block" />
            <div className="hidden h-full w-full border-l border-dashed border-zinc-200 md:block" />
            <div className="hidden h-full w-full border-l border-dashed border-zinc-200 md:block" />
            <div className="h-full w-full border-x border-dashed border-zinc-200" />
          </div>
        </div>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
